---
name: autofix.ci
on: pull_request
permissions: {}
jobs:
  autofix:
    runs-on: ubuntu-24.04
    permissions: {}
    timeout-minutes: 15
    steps:
      - uses: suzuki-shunsuke/go-autofix-action@13021ffe2dd68264a74ff8b11d3a16e19ddcc7a5 # v0.1.5
        with:
          aqua_version: v2.45.0
  status-check:
    runs-on: ubuntu-24.04
    if: failure()
    timeout-minutes: 10
    permissions: {}
    needs:
      - autofix
    steps:
      - run: exit 1
