---
name: Update a GitHub Project
on:
  workflow_dispatch: {}
  # schedule:
  #   - cron: "*/10 * * * *"
jobs:
  update-project:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: aquaproj/aqua-installer@82d0e83878a8657c4a6f2ff1755d3bfbfc67f329 # v4.1.0
        with:
          aqua_version: v2.64.0
        env:
          GITHUB_TOKEN: ${{github.token}}
      - run: ghproj -v
        env:
          GITHUB_TOKEN: ${{github.token}}
      - run: ghproj add
        env:
          GITHUB_TOKEN: ${{secrets.GH_PAT}}
      - run: |
          state=$(gh issue view "$ISSUE_NUMBER" --json state -q .state)
          if [ "$state" = "CLOSED" ]; then
            gh issue reopen "$ISSUE_NUMBER" -c "CI failed. $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
          fi
        if: failure()
        env:
          ISSUE_NUMBER: "24"
          GITHUB_TOKEN: ${{github.token}}
      - run: |
          gh issue close "$ISSUE_NUMBER"
        env:
          ISSUE_NUMBER: "24"
          GITHUB_TOKEN: ${{github.token}}
